// @generated Code generated by gen-atomicint.

// Copyright (c) 2020-2023 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package atomic

// Uint32 is an atomic wrapper around uint32.
type Uint32 struct {
	_ nocmp // disallow non-atomic comparison

	v uint32
}

// NewUint32 creates a new Uint32.
func NewUint32(val uint32) *Uint32 { _ = "STUB: not implemented"; return nil }

// Load atomically loads the wrapped value.
func (i *Uint32) Load() uint32 { _ = "STUB: not implemented"; return 0 }

// Add atomically adds to the wrapped uint32 and returns the new value.
func (i *Uint32) Add(delta uint32) uint32 { _ = "STUB: not implemented"; return 0 }

// Sub atomically subtracts from the wrapped uint32 and returns the new value.
func (i *Uint32) Sub(delta uint32) uint32 { _ = "STUB: not implemented"; return 0 }

// Inc atomically increments the wrapped uint32 and returns the new value.
func (i *Uint32) Inc() uint32 {
	_ = "STUB: not implemented"

	// Dec atomically decrements the wrapped uint32 and returns the new value.
	return 0
}

func (i *Uint32) Dec() uint32 {
	_ = "STUB: not implemented"

	// CAS is an atomic compare-and-swap.
	//
	// Deprecated: Use CompareAndSwap.
	return 0
}

func (i *Uint32) CAS(old, new uint32) (swapped bool) { _ = "STUB: not implemented"; return false }

// CompareAndSwap is an atomic compare-and-swap.
func (i *Uint32) CompareAndSwap(old, new uint32) (swapped bool) {
	_ = "STUB: not implemented"
	return false
}

// Store atomically stores the passed value.
func (i *Uint32) Store(val uint32) { _ = "STUB: not implemented"; return }

// Swap atomically swaps the wrapped uint32 and returns the old value.
func (i *Uint32) Swap(val uint32) (old uint32) { _ = "STUB: not implemented"; return 0 }

// MarshalJSON encodes the wrapped uint32 into JSON.
func (i *Uint32) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON decodes JSON into the wrapped uint32.
func (i *Uint32) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }

// String encodes the wrapped value as a string.
func (i *Uint32) String() string { _ = "STUB: not implemented"; return "" }
